
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Puteri Citra Dewi
 */
public class FormLaundry extends javax.swing.JFrame {

    /**
     * Creates new form FormLaundry
     */
    public FormLaundry() {
        initComponents();
    }
    
    public int totalHarga;
    
    public void reset(){
        optionJenisCuci.setSelectedItem("Pilih");
        txtBayar.setText("");
        txtBerat.setText("");
        txtHarga.setText("");
        txtTotalHarga.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        optionJenisCuci = new javax.swing.JComboBox<>();
        txtBayar = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtBerat = new javax.swing.JTextField();
        txtTotalHarga = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bayar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Laundry Bangcit");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jenis Cuci");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Harga/kg");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Berat");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Harga");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        optionJenisCuci.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        optionJenisCuci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Cuci Kering", "Cuci Basah", "Cuci Setrika" }));
        optionJenisCuci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionJenisCuciActionPerformed(evt);
            }
        });
        jPanel1.add(optionJenisCuci, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 180, 30));

        txtBayar.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        jPanel1.add(txtBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 180, 30));

        txtHarga.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        jPanel1.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 180, 30));

        txtBerat.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        txtBerat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBeratKeyReleased(evt);
            }
        });
        jPanel1.add(txtBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 180, 30));

        txtTotalHarga.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        jPanel1.add(txtTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 180, 30));

        btnBatal.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 90, -1));

        btnTransaksi.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        btnTransaksi.setText("Transaksi");
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        jPanel1.add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 430, 500);

        setSize(new java.awt.Dimension(445, 505));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        reset();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void optionJenisCuciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionJenisCuciActionPerformed
        if (optionJenisCuci.getSelectedItem().toString().equalsIgnoreCase("Pilih")) {
            txtHarga.setText("0");
        } else if (optionJenisCuci.getSelectedItem().toString().equalsIgnoreCase("Cuci Kering")) {
            txtHarga.setText("4000");
        } else if (optionJenisCuci.getSelectedItem().toString().equalsIgnoreCase("Cuci Basah")) {
            txtHarga.setText("3000");
        } else if (optionJenisCuci.getSelectedItem().toString().equalsIgnoreCase("Cuci Setrika")) {
            txtHarga.setText("5000");
        }
    }//GEN-LAST:event_optionJenisCuciActionPerformed

    private void txtBeratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBeratKeyReleased
        int harga = Integer.parseInt(txtHarga.getText());
        int berat = Integer.parseInt(txtBerat.getText());
        totalHarga = harga*berat;
        txtTotalHarga.setText(String.valueOf(totalHarga));
    }//GEN-LAST:event_txtBeratKeyReleased

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
//        int totalHarga = Integer.parseInt(txtTotalHarga.getText());
        int bayar = Integer.parseInt(txtBayar.getText());
        if (txtBayar.getText().isEmpty() || txtBerat.getText().isEmpty() || txtHarga.getText().isEmpty() || txtTotalHarga.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data harus diisi");
        } else if (totalHarga > bayar) {
            JOptionPane.showMessageDialog(null, "Uang anda kurang");
            txtBayar.setText("");
        } else {
            int kembali = bayar - totalHarga;
            String kembalian = Integer.toString(kembali);
            JOptionPane.showMessageDialog(null, "Kembalian Anda : \n"+kembalian);
            reset();
        }
    }//GEN-LAST:event_btnTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLaundry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> optionJenisCuci;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtBerat;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtTotalHarga;
    // End of variables declaration//GEN-END:variables
}
